language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install 'pytest>=2.9' 'pylint'
  - pip install -e .
script:
  - pylint --rcfile=.pylintrc api_object_schema tests setup.py
  - pytest tests
